name: Build PyInstaller Executable

on:
  push:
    branches: [ main ]
  workflow_dispatch:

jobs:
  build:
    runs-on: windows-latest

    steps:
    - name: Checkout code
      uses: actions/checkout@v4

    - name: Set up Miniconda
      uses: conda-incubator/setup-miniconda@v2
      with:
        auto-update-conda: true
        python-version: 3.10
        environment-file: environment.yml
        activate-environment: flowcytometertool
        auto-activate-base: false

    - name: Install PyInstaller
      shell: bash -l {0}
      run: conda install -c conda-forge pyinstaller

    - name: Build executable with PyInstaller
      shell: bash -l {0}
      run: pyinstaller --debug=imports trainer_lucinda_version.spec

    - name: Upload executable
      uses: actions/upload-artifact@v4
      with:
        name: distributable
        path: dist/**
