name: continuousintegration

on:
  push:
    tags:
      - '*'

jobs:
  build:
    runs-on: ubuntu-24.04

    steps:
    - name: Checkout repository
      uses: actions/checkout@v4

    - name: Install Miniconda
      run: |
        wget https://repo.anaconda.com/miniconda/Miniconda3-latest-Linux-x86_64.sh -O miniconda.sh
        bash miniconda.sh -b -p $HOME/miniconda
        export PATH="$HOME/miniconda/bin:$PATH"
        conda init bash
        source $HOME/.bashrc  # Ensure the shell is reloaded

    - name: Create Conda environment
      run: |
        conda env create -f environment.yml

    - name: Run backend logic without GUI
      run: |
        source $HOME/miniconda/etc/profile.d/conda.sh
        conda activate /usr/share/miniconda/envs/flowcytometertool
        python trainer_lucinda_version.py --nogui

    - name: Create release
      id: create_release
      uses: actions/create-release@v1
      env:
        GITHUB_TOKEN: ${{ secrets.GITHUB_TOKEN }}
      with:
        tag_name: ${{ github.ref }}
        release_name: "Release ${{ github.ref }}"
        draft: false
        prerelease: false
